[build]
  command = "npm install --legacy-peer-deps && npm run build && npx convex deploy"

  publish = ".next"
  environment = { NODE_VERSION = "20", PRISMA_GENERATE_DATAPROXY = "false" }

[[plugins]]
  package = "@netlify/plugin-nextjs"