import type { Metadata } from "next";
import "./globals.css";
import "@/css/editor.scss"
import {Inter} from "next/font/google";
import Provider from "./documents/[id]/provider";
import { Toaster } from "@/components/ui/sonner";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({subsets: ["latin"]});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <Provider>
            {children}
            <Toaster />
          </Provider>
        </div>
      </body>
    </html>
  );
}
